language: generic
sudo: false
env:
  - VERSION="5.8"
install:
  - curl -LO https://github.com/polyml/polyml/archive/v${VERSION}.tar.gz
  - tar xf v${VERSION}.tar.gz
  - cd polyml-${VERSION} && ./configure --prefix=$HOME/.local && make && make install && cd -
  - export PATH=$PATH:$HOME/.local/bin
  - which poly
script:
  - bin/fetch-configlet
  - bin/configlet lint .
  - make travis
